services:
  postgres:
    container_name: my-hotel-postgres
    image: postgres:15
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: server
    image: my-hotel-server
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - 7000:7000
    command: npm run start:dev
    restart: always
    depends_on:
      - postgres

  client:
    container_name: client
    image: my-hotel-client
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - 8080:8080
    command: npm run dev
    restart: always
    depends_on:
      - server

volumes:
  postgres-data:
